name: mhist_pipeline
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.11
 - pip
 - pytorch
 - torchvision
 - pandas
 - numpy
 - scikit-learn
 - matplotlib
 - pip:
    - pytest
    - lightning
    - wandb
    - fastapi
    - uvicorn
    - python-dotenv
    - transformers